### ISSUE TITLE
Application carsh when try to analyze for malicious binary

### ISSUE THREAD

**Issue by simakhan785** [NtRaiseHardError/Dreadnought#1]
Hi, I am try to experimenting with Dreadnought for detecting process injection. I have try to build the application on Visual studio 15 and SDK 10.0.586. However, in the build I get error on ReadProcessMemory and WriteProcessMemory call last argument (declared as DWORD) - giving some conversion issue. After, I had solve the issue it builds but with lots warning. However, when I try to analyze any application, the dreadnought application crashes. Pls. help.

**Comment by simakhan785** [comment]
Also, Dreadnought application is crashing when the application to scan is 64-bit

**Comment by NtRaiseHardError** [comment]
Sorry, I did not design this application for 64-bit architectures. The hooking DLL is targeted for x86 as stated in its name. What applications are you analysing? Are they 64-bit?
